# dependentOrigination
A Discourse on the doctrine of dependent origination

Editor’s Foreword
The late Venerable Mahāsi Sayādaw’s discourse on Dependent Origination was delivered in several sections to meditators practising intensively at his meditation centre in Rangoon. The tapes were meticulously transcribed, then translated into English by U Aye Maung. His translation was first published in March 1982, and reprinted in Penang in 1989.

This new edition has been prepared with the aim of making it more accessible by removing Pāḷi words wherever possible, and by simplifying the English. Although many changes have been made to the original translation, they are mostly grammatical ones. The main content of the Venerable Sayādaw’s discourse has been carefully preserved, but it is now much easier to read than it was. A lot of effort has also gone into improving the typesetting and layout. I am indebted to Christine Fitzmaurice-Glendining for her help with the grammar. U Hla Kyaing, Barry Durrant and Andrew Crowe also made many helpful suggestions.

I have added a few footnotes and illustrations to clarify the text where I thought it would be helpful. I have updated the index to help the reader locate topics of particular interest more quickly. It also serves as a glossary of the Pāḷi terms used in this book.

This 2013 edition has been updated with bookmarks and cross-references for convenient reading as a PDF file, while browsing online. Some minor editions were made and some more footnotes were added.

As with all the Venerable Sayādaw’s discourses, this teaching is not just for the sake of academic knowledge. Although some theoretical knowledge is very helpful for progress in meditation, the Sayādaw stressed the importance of gaining personal experience of the truths taught by the Buddha through the practice of insight meditation.

Only insight into the true nature of one’s own body and mind will put an end to the cycle of suffering, and insight can come about only through deep concentration. Again, concentration is dependent on constant and uninterrupted mindfulness (sati), which requires sustained effort to observe all mental and physical phenomena. In short, one must practise insight meditation systematically and arduously until nibbāna is reached, which is the only way to put an end to suffering. Wishing or hoping is of little use when it comes to the arousing of insight. Intellectual knowledge gained by reading books may be a help, but only if it inspires us to practise and gain personal experience of the Dhamma. If our knowledge remains at the intellectual level, and is not applied on the practical level, it will not lead to insight. As the Doctrine of Dependent Origination teaches, if the conditions are not present, the results cannot arise.

In the words of the Buddha, “What should be done by a teacher for his disciples out of compassion has been done. There are roots of trees and empty places. Meditate, monks, do not be remorseful later.”

There are many meditation centres and monasteries, retreats, and meditation classes. Find a place near you that is conducive to the development of concentration and insight. It could be anywhere — it doesn’t have to be a sacred place, just reasonably quiet and isolated. Learn the correct method from a meditation teacher, or from books if no suitable teacher is available. Then invest sufficient time and effort to get some results.

Bhikkhu Pesala
Seven Kings, London
August 2013

A Discourse on Dependent Origination
Importance of the Doctrine
HE doctrine of dependent origination (Paṭiccasamuppāda) is central to Buddhism. While the Bodhisatta was reflecting deeply on the nature of existence, he realised the truth about Dependent Origination, and attained enlightenment. Before he became the Buddha in his final existence, he pondered aging and death — as did every other Bodhisatta. For it was only after he had seen the misery of aging, disease, and death that he renounced the world in search of the deathless.

All living beings want to avoid these misfortunes but they cannot escape. These misfortunes pursue them relentlessly from one existence to the next in a perpetual process of birth, aging, and death. For example, the fate of chickens and ducks is terrible. Some are eaten while still in the eggs. Even if they hatch, they live for just a few weeks, and are killed as soon as they put on sufficient weight. They are born only to be killed for human consumption. If it is the fate of living beings to be repeatedly killed like this, then it is a very gloomy and frightful prospect. Nevertheless, chickens and ducks seem content with their lot in life. They apparently enjoy life — quacking, crowing, eating, and fighting with one another. They may think that they have plenty of time to enjoy life, though in fact they may live for just a few days or months.

The span of human life is not very long either. For someone in their fifties or sixties their youth may seem as recent as yesterday. Sixty or seventy years on earth is a day in the life of a deva. The life of a deva is also very brief in the eyes of a Brahmā, who may live for the duration of the world system. However, even the lifespan of a Brahmā, who outlives hundreds of worlds, is insignificant compared to eternity. Celestial beings, too, eventually have to die. Although they are not subject to disease and marked senility, age tells on them imperceptibly in due course.

Reflections of the Bodhisatta
Reflecting on the cause of aging, the Bodhisatta traced back the chain of Dependent Origination from the end to the beginning. He found that aging (jarā) and death (maraṇaṃ) have their origin in birth (jāti), which in turn is due to becoming (bhava). Becoming stems from attachment (upādāna), which is caused by craving (taṇhā). Craving arises from the feeling (vedanā) produced by contact (phassa), which in turn depends on the six sense-bases (saḷāyatana) such as the eye and visual form. Sense-bases are the product of mind and matter (nāmarūpa), which depend on consciousness (viññāṇa). Consciousness is, in turn, dependent on mind and matter (nāmarūpa). The full Pāḷi texts on Dependent Origination attribute consciousness to mental formations (saṅkhārā), and mental formations to ignorance (avijjā). However, the Bodhisatta’s reflection was confined to the interdependence of mind and matter. In other words, he reflected on the correlation between consciousness and mind and matter, leaving out of account the former’s relationship to past existence. We may assume, therefore, that for meditators, reflection on the present life will suffice for the successful development of insight.

Concerning the correlation between consciousness, and mind and matter, the Bodhisatta reasoned, “This consciousness has no cause other than mind and matter. Mind and matter produce consciousness, and consciousness arises from mind and matter. So, from the correlation between consciousness, and mind and matter, birth, aging, and death arise — there may be successive births or successive deaths.” Moreover, consciousness causes mind and matter, and mind and matter give rise to the six sense-bases. Dependent on the sense-bases contact arises, contact leads to feeling, feeling gives rise to craving, which develops into attachment, and attachment results in rebirth. This, in turn, leads to aging, death, anxiety, grief, and other kinds of mental and physical suffering.

Then the Bodhisatta reflected on the reverse order of Dependent Origination. Without consciousness, mind and matter could not arise; without mind and matter, the sense-bases could not arise; and so on. Breaking the first link in the chain of causation eradicates the suffering that has constantly beset us throughout saṃsāra. After this reflection on Dependent Origination in its forward and reverse orders, the Bodhisatta contemplated the nature of the aggregates of attachment. Then he attained the successive insights and fruition on the Noble Path, and finally became a fully enlightened Buddha. Every Bodhisatta attains supreme enlightenment after such contemplation. They are not taught how to practise, but because of their perfections (pāramī) accumulated through innumerable lifetimes, they can contemplate in this way and so attain enlightenment.

Beyond Reasoning and Speculation
When the Buddha was first considering whether or not to teach, he thought, “This truth that I have realised is very profound. Though it is sublime and conducive to inner peace, it is hard to understand. Since it is subtle and not accessible to mere intellect and logic, it can be realised only by the wise.” Great thinkers from all cultures have thought deeply about freedom from the misery of aging, disease, and death, but such freedom would mean nibbāna, which is beyond the scope of reason and intellect. It can be realised only by practising the right method of insight meditation. Most great thinkers have relied on intellect and logical reasoning to conceive various principles for the well-being of humanity. As these principles are based on speculations, they do not help anyone to attain insight, let alone the supreme goal of nibbāna. Even the lowest stage of insight, namely, analytical knowledge of body and mind (nāmarūpa-pariccheda-ñāṇa), cannot be realised intellectually. This insight dawns only when one observes the mental and physical process using the systematic method of setting up mindfulness (satipaṭṭhāna), and when, with the development of concentration, one distinguishes between mental and physical phenomena — for example, between the desire to bend the hand and the bent hand, or between the sound and the hearing. Such knowledge is not vague and speculative, but vivid and empirical.

The Pāḷi texts say that mind and matter are constantly changing, and that we should observe their arising and passing away. However, for the beginner in meditation, this is easier said than done. One has to exert strenuous effort to overcome mental hindrances (nīvaraṇa). Even freedom from such hindrances only helps one to distinguish between mind and matter; it does not ensure insight into the process of their arising and passing away. This insight is attained only on the basis of strong concentration and keen perception developed through the practice of mindfulness. Constant mindfulness of the arising and passing away of phenomena leads to insight into their characteristics of impermanence (anicca), unsatisfactoriness (dukkha), and not-self (anatta). However, this is merely a lower stage of insight, which is still far from the Path and its Fruition. So, the Dhamma is described as something beyond logic and intellect.

Dhamma is Only for the Wise
The Dhamma is subtle (nipuṇo) and can be realised only by the wise (paṇḍitavedanīyo). Here ‘the wise’ refers to those who have wisdom relating to insight, the Path, and nibbāna. The Dhamma has nothing to do with the secular knowledge possessed by world philosophers, religious leaders, writers or great scientists. However, anyone can realise it if they contemplate mental and physical phenomena at the moment they arise. If they pass progressively through the stages of insight, they will attain the Noble Path and its Fruition.

When the Buddha considered the nature of living beings, he found that most were immersed in sensual pleasures. Of course, there were a few exceptions like his five former companions in the forest retreat, or the two brahmins who were later to become the chief disciples of the Buddha. Most people, however, regard the enjoyment of pleasure as the supreme goal in life. Ordinary men and devas esteem such pleasure because they have no sense of the higher values, such as deep concentration, insight, and nibbāna. They are like children who delight in playing with their toys the whole day. Sensual pleasures do not appeal to Buddhas and Arahants. A person who delights in sensuality may be compared to villagers living in a remote rural area. To city-dwellers these places seem totally destitute, with poor food, coarse clothing, primitive dwellings, and muddy footpaths, but the villagers are happy, and never think of leaving. Similarly, pleasure-seekers are so enamoured with their families, friends, and possessions that they cannot think of anything more noble and feel ill at ease without the stimulus of sense objects. It is hard for them to appreciate the subtle, profound doctrine of Dependent Origination, and nibbāna.

Dhamma is Profound
The Buddha’s teaching has little attraction for the majority since it is diametrically opposed to sensuality. Even an ordinary sermon, let alone a discourse on nibbāna, is unpopular if it has no sensual appeal. People do not seem to be interested in our teaching, and no wonder, for it lacks melodious recitation, anecdotes, jokes, and similar attractions. It is acceptable only to those who have practised meditation or who are earnestly seeking spiritual peace and freedom from the defilements (kilesa). It is a mistake to deprecate the suttas by confusing them with talks containing stories and jokes. Discourses such as the Anattalakkhaṇa Sutta and the Satipaṭṭhāna Sutta differ from popular sermons in that they are profound. The doctrine of Dependent Origination belongs to the Sutta Piṭaka, but it can be classified as Abhidhamma because it is explained in the analytical way typical of the Abhidhamma Piṭaka. Since this teaching also uses the analytical method, some people confuse it with the Abhidhamma and cannot follow it, much less attain the Path and nibbāna, which it emphasises. Dependent Origination is hard to comprehend because it concerns the correlation between causes and effects. Before the Buddha proclaimed this teaching, it was difficult to understand that no self exists independently of the law of causation.

The Commentaries also point out the abstruse character of the doctrine. According to them, four subjects are very profound: the Four Noble Truths, the nature of a living being, the nature of rebirth, and Dependent Origination.

First, it is hard to accept the truths about suffering, its cause, its cessation, and the way to its cessation. Appreciating these truths is hard enough; it is still harder to teach them to other people. Secondly, it is hard to understand that a living being is just a psychophysical process without any abiding self, and that this process is subject to the law of kamma, which determines one’s future according to one’s actions. Thirdly, it is hard to see how rebirth takes place because of defilements and kamma, without the transfer of mind and matter from a previous life. Lastly, Dependent Origination is hard to comprehend fully, because it embraces the above three abstruse teachings. Its forward order concerns the first two noble truths, the nature of a living being and rebirth, while its reverse order encompasses the other two truths. So the doctrine is very difficult to grasp or to teach. Explaining it to one who has attained the Path and nibbāna, or to one who has studied the Tipiṭaka, may be easy. However, it will not mean much to someone who has neither insight nor scriptural knowledge.

The writer of the Commentary on Dependent Origination was qualified to explain it because he had perhaps attained the lower stages of the Path. At least, he must have had a thorough knowledge of the Tipiṭaka. He probably stressed its profundity so that it might be studied more seriously, comparing his difficulty in explaining it to the plight of a man who has jumped into the ocean and cannot touch the bottom. He says that he wrote the exegesis based on the Tipiṭaka and the old Commentaries handed down by oral tradition. The same may be said of my teaching. Since the doctrine is hard to explain, one should pay special attention to it. If one follows the teaching superficially, one will understand nothing, and without a reasonable knowledge of the doctrine one is bound to suffer in many existences.

The substance of the teaching is as follows: Dependent on ignorance (avijjā) mental formations (saṅkhārā) arise. From mental-formations rebirth-consciousness (viññāṇa) arises. Consciousness gives rise to mind and matter (nāmarūpa). From mind and matter, the six sense-bases (saḷāyatana) arise. From the six sense-bases, contact (phassa) arises. Contact causes feeling (vedanā), feeling leads to craving (taṇhā), and from craving, attachment (upādāna) results. Attachment produces becoming (bhava), and from becoming birth (jāti) arises. Finally, birth leads to aging (jarā), death (maraṇaṃ), grief (soka), lamentation (parideva), pain (dukkha), sorrow (domanassa), and despair (upāyāsa). In this way the whole mass of suffering arises.

What is Ignorance?
According to the Buddha, avijjā is ignorance of the Four Noble Truths: the truths about suffering, its cause, its cessation and the way to its cessation. In a positive sense avijjā implies misconception or illusion. It makes us take what is false and illusory as true and real. We are led astray, and so avijjā is sometimes called ignorance regarding the way of practice. In this sense it differs from ordinary ignorance. If someone does not know the name of a man or a village, it does not necessarily mean that they are deluded, whereas being ignorant of Dependent Origination means more than merely not knowing. Avijjā is more like the delusion of a person who has lost all sense of direction and so thinks that east is west or that north is south. The person who does not understand the truth of suffering has an optimistic view of life, although life is full of pain and sorrow (dukkha).¹ It is a mistake to search for the truth of suffering in books as it is to be found in one’s own body and mind. Seeing, hearing, and all other psychophysical phenomena arising from the six senses are unsatisfactory because they are impermanent (anicca), unreliable (aniyata), and do not comply with one’s wishes (anattā). Life may end at any moment and so it is full of pain and suffering. However, this dukkha cannot be realised by those who regard existence as blissful and satisfying. Their efforts to secure what they believe are pleasant sense-objects, such as beautiful sights, melodious sounds, delicious food and so forth, are due to their illusions about life. This ignorance is like the green eyeglass that makes a horse eat dry grass. Similarly, living beings are immersed in sensuality because they see everything through rose-tinted glasses, harbouring illusions about the pleasant nature of sense-objects, and about mind and matter.

A blind man could easily be deceived by a confidence trickster who offered him a worthless garment, saying that it was an expensive one. The blind man would believe him and would like the garment very much. However, if he recovered his sight, he would be disillusioned and would throw it away at once. In the same way, an ignorant person enjoys life as long as he or she is oblivious to impermanence, unsatisfactoriness, and not-self, but becomes disenchanted when insight reveals the odious nature of existence.

Introspection of mind and matter, or insight meditation, is different from academic knowledge. Insight meditation means thoroughly observing and ceaselessly contemplating all the psychophysical phenomena that comprise the sense-objects and sense-consciousness. As concentration develops, one realises how all phenomena arise and instantly vanish, which leads to a full understanding of their nature. Delusion blinds us to reality only because we are unmindful. Unmindfulness leads us to believe in the illusions of a man, a woman, a hand, a leg, etc., in the conventional sense. We do not know that seeing, for instance, is merely a psychophysical process that arises and vanishes, and that it is impermanent, unsatisfactory, and not-self. Since most people do not meditate, they die without knowing anything about mind and matter. The true nature of the psychophysical process can be realised only by a mindful person. However, this insight does not occur initially when concentration is undeveloped. Delusion, which is the usual state of mind, precedes contemplation so the beginner does not gain a clear insight into mind and matter. It is only through steadfast practice that concentration and perception develop and lead to insight knowledge. If, for example, while practising mindfulness, one feels an itch, one is barely aware of being itchy. One does not think that it is the hand, the leg, or any other part of the body that is itchy. The thought “I feel itchy,” regarding oneself as the victim of itchiness, does not occur. Only the continuous sensation of itchiness is known. This sensation does not remain permanently, but passes away as soon as one notes it. The observing mind promptly notes every phenomenon as it occurs, leaving no room for the illusion of hand, leg, and so forth.

Delusion dominates the unmindful person blinding him or her to the unsatisfactoriness of all sense-objects, concealing pain behind pleasure. Avijjā means both ignorance of the truth and the misconception that distorts reality. Since they do not know the truth of suffering, people seek pleasant sense-objects. Thus ignorance leads to effort and karmic activity (saṅkhārā). According to the scriptures, mental formations arise because of ignorance, but between them there are the two links of craving and attachment. Ignorance leads to craving, which develops into attachment. Craving and attachment stem from the desire for pleasure and are explicitly mentioned in the middle part of the doctrine of Dependent Origination. When the past is fully described, ignorance, craving, attachment, kamma, and mental formations are all included.

Ignorance of the Origin of Suffering
People do not know that craving is the cause of suffering. On the contrary, they believe that attachment makes them happy, that without attachment life would be dreary. So they constantly seek pleasant sense-objects: food, clothing, companions, and so forth. Without these objects of attachment they feel ill at ease, and find life dull. For ordinary people, life without attachment would be wholly without enjoyment. It is craving that conceals the unpleasantness of life and makes it seem agreeable, but for the Arahant, who has eradicated craving, indulgence is impossible. He is always bent on nibbāna, the cessation of suffering.

Craving cannot exert much pressure on meditators when they become absorbed in the practice, so some do not enjoy life as much as they did before. On returning from the retreat they grow bored at home and feel ill at ease in the company of their families. To other people, meditators may seem conceited, but in fact their behaviour is a sign that they have lost interest in the everyday world. However, if they cannot overcome sensual desire, this boredom is temporary and they usually re-adjust to domestic life in due course. Their families need not worry over this mood or behaviour for it is hard to become thoroughly disenchanted with household life. Meditators should check to see just how much they are disenchanted with life. If the desire for pleasure lingers, they are still in the grip of craving.

Without craving, people feel discomfited. In association with ignorance, craving blinds them to suffering and creates the illusion of happiness. So they frantically seek sources of pleasure. Consider, for example, people’s fondness for films and plays. These entertainments cost time and money but craving makes them irresistible, although they seem troublesome to one who has no interest in them. A more obvious example is smoking. The smoker enjoys inhaling the tobacco smoke, but to the non-smoker it is a kind of self-inflicted suffering. Non-smokers are free from all the troubles that beset the smoker. They lead a relatively carefree and happy life because they do not crave for tobacco. Craving as the source of suffering is also obvious in the habit of betel-chewing. Some people enjoy it, although it is a troublesome habit.

Like the smoker and the betel-chewer, people seek to gratify their craving, and this effort is the basis of rebirth, which leads to aging, disease, and death. Suffering, and craving as its cause, are evident in everyday life, but it is hard to accept these truths because they are profound. One cannot realise them through mere reflection but only through the practice of insight meditation.

Ignorance of the Cessation of Suffering and the Path
Avijjā also means ignorance of the cessation of suffering and the Path leading to it. These two truths are also profound. The truth of the cessation of suffering (nirodhasacca) concerns nibbāna, which can be realised only by the Noble Path. The truth of the Path (maggasacca) is known with certainty only by the meditator who has attained nibbāna. No wonder, then, that many people are ignorant of these truths. Ignorance of the end of suffering is widespread, so world religions describe the supreme goal in diverse ways. Some say that suffering will cease automatically in due course. Some regard sensual pleasure as the highest bliss and reject the idea of future life. This variety of beliefs is due to ignorance of the real nibbāna. Even among Buddhists some hold that nibbāna is a realm or sort of paradise, and many arguments are put forward about it. These various views show how hard it is to understand nibbāna.

Nibbāna is the total extinction of the incessant psychophysical process that occurs because of conditions. So, according to Dependent Origination, ignorance, mental formations, etc., produce mind and matter and so forth. This causal process involves aging, death, and other misfortunes. If ignorance is extinguished by the Noble Path, so are its effects. This complete extinction of suffering is nibbāna. For example, a lamp that is refuelled will keep on burning, but if it is not refuelled the flame will go out. Likewise, for the meditator on the Noble Path who has attained nibbāna, all the causes such as ignorance have become extinct and so have all the effects such as rebirth. This means the total extinction of suffering (nibbāna), which one must understand and appreciate before realising it.

The idea of nibbāna does not appeal to those with a strong craving for life. To them, the cessation of the psychophysical process would mean nothing less than death. Nevertheless, intellectual acceptance of nibbāna is necessary because attainment of the supreme goal depends upon one’s wholehearted and persistent effort.

Knowledge of the Path to the end of suffering is also vital. Only a Buddha can proclaim the right path; it is impossible for anyone else to do so, whether they are a deva, a Brahmā, or a human being. Nevertheless, speculations about the right path abound. Some advocate ordinary morality such as love, altruism, patience or charity, while others stress the practice of mental absorption (jhāna). All these practices are commendable, for they lead to relative well-being in the celestial realms and can be helpful to attain nibbāna. They do not, however, ensure freedom from suffering, for on their own they are not sufficient to attain nibbāna.

Some resort to self-mortification such as fasting, nakedness, and so forth; while others worship deities or animals, or live like animals. From the Buddhist point of view all these are ‘sīlabbataparāmāsa,’ which refers to any practice not concerned with the Noble Eightfold Path.

The Noble Eightfold Path comprises right view, right thought, right speech, right action, right livelihood, right effort, right mindfulness, and right concentration. The path is of three kinds: the basic path, the preliminary path, and the Noble Path. Of these, the Noble Path is the most vital. However, this path should not be the primary objective of the meditator nor does it require one to spend much time and energy on it. For when insight on the preliminary path matures, insight on the Noble Path occurs for a thought-moment. Though it requires much time and effort to produce fire by friction, ignition takes just a moment. Similarly, the insight on the Noble Path is instantaneous but it presupposes much development of insight on the preliminary path.

Right View
Vipassanā is the insight that occurs at every moment of contemplation. One who notes all psychophysical phenomena becomes aware of their true nature. Thus one focuses attention on the bending of one’s arms or legs and discerns the elements of rigidity and motion. This means right view concerning the element of motion (vāyodhātu). Lack of mindfulness will give rise to false perceptions like: “It is a hand,” “It is a man,” and so forth. Only the mindful meditator sees things as they really are. The same may be said of right view regarding sensations in the body, e.g. heat or pain, and mental activities, e.g. imagination or intention. When the mind becomes steady and calm, one finds that mental and physical phenomena arise and vanish, and so one gains insight into their intrinsic nature. Right view implies right thought and other associated states on the Path. Insight on the Path occurs at every moment of contemplation. With the perfection of insight into the three characteristics, one realises nibbāna. So, if nibbāna is to be realised right now, the practice of insight meditation is essential. One who cannot yet practise meditation should focus on the path that is the basis of insight practice. This basic path means doing meritorious deeds motivated by the belief in kamma. In other words, they should practise charity, morality, and meditation with the aspiration to attain nibbāna.

All the paths — the basic, the preliminary, and the Noble Path — form the eightfold path leading to nibbāna. In particular, one must recognise the Noble Path as the dhamma that is to be sought after, cultivated, and revered. Such an attitude is a prerequisite for strenuous effort in meditation. One must fully appreciate the value of insight meditation and know how to practise it.

Some people are ignorant of the way to nibbāna. Furthermore, they belittle the nibbāna-oriented meritorious deeds of others. Some deprecate the teaching and practice of others though they themselves have never practised insight meditation effectively. Some criticise the right method because they are attached to their own wrong method. All these people have misconceptions about the right path. It is ignorance not to know that charity, morality, and meditation lead to nibbāna and it is ignorance too, to regard them as harmful to one’s interests. The most harmful ignorance is ignorance of, and illusion about, the right method of contemplation.

Ignorance of the right path is the most terrible form of ignorance. It makes its victims blind to meritorious deeds and creates illusions, preventing them from attaining even human happiness or divine bliss, let alone the Noble Path and nibbāna. Yet most people remain steeped in ignorance, unmindful of the need to devote themselves to charity, morality, and meditation.
